@baseUrl = http://localhost:3000

### Health Check
GET {{baseUrl}}/api/status

### Login válido
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Login inválido
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "username": "usuario",
  "password": "senha"
}